site_name: Command Line Conflict
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green

plugins:
  - include-markdown
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference: API.md
  - ECS Architecture: ECS.md
  - Contributing: Contributing.md
  - Security: Security.md
  - Maps: Maps.md
  - Project Structure: ProjectStructure.md
  - Changelog: CHANGELOG.md
  - Agent Tasks: agents.md
