name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDL_VIDEODRIVER: dummy

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Format Check (Black)
      run: |
        black --check .
    - name: Import Sort Check (isort)
      run: |
        isort --check .
    - name: Lint with Flake8
      run: |
        flake8 .
    - name: Lint with Pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=9.0
    - name: Type Check with Mypy
      run: |
        mypy command_line_conflict
    - name: Test with pytest
      run: |
        pytest --cov=command_line_conflict --cov-report=html --cov-report=term tests/
    - name: Build documentation
      run: |
        mkdocs build --strict
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov
